version: "3.3"

services:
  db:
    container_name: dbpayments
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  api:
    container_name: apipayments
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MNEMONIC=${MNEMONIC}
        - INFURA_API_KEY=${INFURA_API_KEY}
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/db
    ports:
      - "8000:3000"
    depends_on:
      - db
